language: node_js
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: '8'
      script: npm run lint && npm test
      env: CI=test
    - node_js: '6'
      script: npm run lint && npm test
      env: CI=tests 6
before_install:
  - npm install -g npm@latest
