language: node_js
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: "9"
      script: npm run lint && npm test
      env: CI=test 9
    - node_js: "9"
      script: npm test -- --runInBand --coverage
      env: CI=coverage
    - node_js: "8"
      script: npm run lint && npm test
      env: CI=test
before_install:
  - npm install -g npm@latest
after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi
